"""上海六年级单元复习卷的公开目录范围与人工整理知识点。"""

MATH_SOURCE_FIRST = "上海六年级第一学期《数学（试用本）》目录"
MATH_SOURCE_SECOND = "上海六年级第二学期《数学（试用本）》目录"
ENGLISH_SOURCE_FIRST = "上海六年级第一学期《英语（牛津上海版）（试用本）》目录"
ENGLISH_SOURCE_SECOND = "上海六年级第二学期《英语（牛津上海版）（试用本）》目录"


CURRICULUM_UNITS = [
    {
        "id": "math-6a-divisibility",
        "subject": "math",
        "semester": "first",
        "title": "第一章 数的整除",
        "knowledge_points": [
            "整数和整除的意义", "因数和倍数", "能被2、5整除的数", "素数、合数与分解素因数",
            "公因数和最大公因数", "公倍数和最小公倍数",
        ],
        "source_note": MATH_SOURCE_FIRST,
    },
    {
        "id": "math-6a-fractions",
        "subject": "math",
        "semester": "first",
        "title": "第二章 分数",
        "knowledge_points": [
            "分数与除法", "分数的基本性质", "分数的大小比较", "分数的加减法",
            "分数的乘除法", "分数与小数的互化", "分数四则混合运算",
        ],
        "source_note": MATH_SOURCE_FIRST,
    },
    {
        "id": "math-6a-ratio",
        "subject": "math",
        "semester": "first",
        "title": "第三章 比和比例",
        "knowledge_points": ["比的意义", "比的基本性质", "比例", "百分比的意义", "百分比的应用", "等可能事件"],
        "source_note": MATH_SOURCE_FIRST,
    },
    {
        "id": "math-6a-circle",
        "subject": "math",
        "semester": "first",
        "title": "第四章 圆和扇形",
        "knowledge_points": ["圆的周长", "弧长", "圆的面积", "扇形的面积"],
        "source_note": MATH_SOURCE_FIRST,
    },
    {
        "id": "math-6b-rational-numbers",
        "subject": "math",
        "semester": "second",
        "title": "第五章 有理数",
        "knowledge_points": [
            "有理数的意义", "数轴", "绝对值", "有理数的加减法", "有理数的乘除法",
            "有理数的乘方", "有理数混合运算",
        ],
        "source_note": MATH_SOURCE_SECOND,
    },
    {
        "id": "math-6b-equations-inequalities",
        "subject": "math",
        "semester": "second",
        "title": "第六章 一次方程（组）和一次不等式（组）",
        "knowledge_points": [
            "方程与方程的解", "一元一次方程", "列方程解应用题", "一元一次不等式",
            "一元一次不等式组", "二元一次方程组", "三元一次方程组",
        ],
        "source_note": MATH_SOURCE_SECOND,
    },
    {
        "id": "math-6b-lines-angles",
        "subject": "math",
        "semester": "second",
        "title": "第七章 线段与角的画法",
        "knowledge_points": ["线段的相等与和差倍", "线段的中点", "角的概念与表示", "角的大小比较", "角的和差倍", "余角与补角"],
        "source_note": MATH_SOURCE_SECOND,
    },
    {
        "id": "math-6b-cuboid",
        "subject": "math",
        "semester": "second",
        "title": "第八章 长方体的再认识",
        "knowledge_points": ["长方体的元素", "长方体直观图", "棱与棱的位置关系", "棱与平面的位置关系", "平面与平面的位置关系"],
        "source_note": MATH_SOURCE_SECOND,
    },
    {
        "id": "english-6a-m1u1-family",
        "subject": "english",
        "semester": "first",
        "title": "Module 1 Unit 1 Family and relatives",
        "knowledge_points": ["family and relatives", "family tree", "How many questions", "present simple"],
        "source_note": ENGLISH_SOURCE_FIRST,
    },
    {
        "id": "english-6a-m1u2-friend",
        "subject": "english",
        "semester": "first",
        "title": "Module 1 Unit 2 I have a good friend",
        "knowledge_points": ["friendship qualities", "adverbs of frequency", "helpful behaviour", "simple descriptions"],
        "source_note": ENGLISH_SOURCE_FIRST,
    },
    {
        "id": "english-6a-m1u3-day-out",
        "subject": "english",
        "semester": "first",
        "title": "Module 1 Unit 3 Spending a day out together",
        "knowledge_points": ["places for outings", "activity plans", "have been to", "going to"],
        "source_note": ENGLISH_SOURCE_FIRST,
    },
    {
        "id": "english-6a-m2u4-jobs",
        "subject": "english",
        "semester": "first",
        "title": "Module 2 Unit 4 What would you like to be?",
        "knowledge_points": ["jobs and workplaces", "would like to be", "reasons with because", "job responsibilities"],
        "source_note": ENGLISH_SOURCE_FIRST,
    },
    {
        "id": "english-6a-m2u5-open-day",
        "subject": "english",
        "semester": "first",
        "title": "Module 2 Unit 5 Open Day",
        "knowledge_points": ["school places", "Open Day activities", "future arrangements", "first next then finally"],
        "source_note": ENGLISH_SOURCE_FIRST,
    },
    {
        "id": "english-6a-m2u6-school",
        "subject": "english",
        "semester": "first",
        "title": "Module 2 Unit 6 Going to school",
        "knowledge_points": ["transport and routes", "How questions", "How long questions", "It takes expressions"],
        "source_note": ENGLISH_SOURCE_FIRST,
    },
    {
        "id": "english-6a-m2u7-rules",
        "subject": "english",
        "semester": "first",
        "title": "Module 2 Unit 7 Rules round us",
        "knowledge_points": ["public signs", "must and must not", "rules in different places", "permission and prohibition"],
        "source_note": ENGLISH_SOURCE_FIRST,
    },
    {
        "id": "english-6a-m3u8-food",
        "subject": "english",
        "semester": "first",
        "title": "Module 3 Unit 8 The food we eat",
        "knowledge_points": ["food groups", "countable and uncountable nouns", "shopping for food", "meal choices"],
        "source_note": ENGLISH_SOURCE_FIRST,
    },
    {
        "id": "english-6a-m3u9-picnic",
        "subject": "english",
        "semester": "first",
        "title": "Module 3 Unit 9 Picnics are fun",
        "knowledge_points": ["picnic food", "shall we", "would like", "agreeing and giving reasons"],
        "source_note": ENGLISH_SOURCE_FIRST,
    },
    {
        "id": "english-6a-m3u10-healthy",
        "subject": "english",
        "semester": "first",
        "title": "Module 3 Unit 10 Healthy eating",
        "knowledge_points": ["healthy diets", "too much and not enough", "food pyramid", "health suggestions"],
        "source_note": ENGLISH_SOURCE_FIRST,
    },
    {
        "id": "english-6a-m3u11-pizza",
        "subject": "english",
        "semester": "first",
        "title": "Module 3 Unit 11 Let's make a pizza",
        "knowledge_points": ["ingredients", "cooking instructions", "need expressions", "process writing"],
        "source_note": ENGLISH_SOURCE_FIRST,
    },
    {
        "id": "english-6b-m1u1-cities",
        "subject": "english",
        "semester": "second",
        "title": "Module 1 Unit 1 Great cities in Asia",
        "knowledge_points": ["Asian cities", "directions and locations", "How far questions", "travel time"],
        "source_note": ENGLISH_SOURCE_SECOND,
    },
    {
        "id": "english-6b-m1u2-airport",
        "subject": "english",
        "semester": "second",
        "title": "Module 1 Unit 2 At the airport",
        "knowledge_points": ["airport vocabulary", "flight information", "have been to", "departure arrangements"],
        "source_note": ENGLISH_SOURCE_SECOND,
    },
    {
        "id": "english-6b-m1u3-festival",
        "subject": "english",
        "semester": "second",
        "title": "Module 1 Unit 3 Dragon Boat Festival",
        "knowledge_points": ["festival vocabulary", "festival history", "past events", "would rather"],
        "source_note": ENGLISH_SOURCE_SECOND,
    },
    {
        "id": "english-6b-m1u4-health",
        "subject": "english",
        "semester": "second",
        "title": "Module 1 Unit 4 Staying healthy",
        "knowledge_points": ["indoor and outdoor activities", "healthy habits", "should suggestions", "favourite activities"],
        "source_note": ENGLISH_SOURCE_SECOND,
    },
    {
        "id": "english-6b-m2u5-future",
        "subject": "english",
        "semester": "second",
        "title": "Module 2 Unit 5 What will I be like?",
        "knowledge_points": ["future appearance", "will statements", "possible jobs", "personal ambitions"],
        "source_note": ENGLISH_SOURCE_SECOND,
    },
    {
        "id": "english-6b-m2u6-seasons",
        "subject": "english",
        "semester": "second",
        "title": "Module 2 Unit 6 Seasonal changes",
        "knowledge_points": ["seasonal weather", "school uniforms", "seasonal activities", "because clauses"],
        "source_note": ENGLISH_SOURCE_SECOND,
    },
    {
        "id": "english-6b-m2u7-transport",
        "subject": "english",
        "semester": "second",
        "title": "Module 2 Unit 7 Travelling in Garden City",
        "knowledge_points": ["public transport", "transport changes", "comparisons", "future transport"],
        "source_note": ENGLISH_SOURCE_SECOND,
    },
    {
        "id": "english-6b-m3u8-wind",
        "subject": "english",
        "semester": "second",
        "title": "Module 3 Unit 8 Windy weather",
        "knowledge_points": ["wind strength", "weather observations", "adverbs of manner", "sequence of events"],
        "source_note": ENGLISH_SOURCE_SECOND,
    },
    {
        "id": "english-6b-m3u9-water",
        "subject": "english",
        "semester": "second",
        "title": "Module 3 Unit 9 Sea water and rain water",
        "knowledge_points": ["water sources", "water uses", "water cycle", "saving water"],
        "source_note": ENGLISH_SOURCE_SECOND,
    },
    {
        "id": "english-6b-m3u10-forests",
        "subject": "english",
        "semester": "second",
        "title": "Module 3 Unit 10 Forests and land",
        "knowledge_points": ["forest resources", "uses of materials", "environmental protection", "cause and effect"],
        "source_note": ENGLISH_SOURCE_SECOND,
    },
    {
        "id": "english-6b-m3u11-fire",
        "subject": "english",
        "semester": "second",
        "title": "Module 3 Unit 11 Controlling fire",
        "knowledge_points": ["fire safety", "safe and unsafe actions", "must and must not", "emergency instructions"],
        "source_note": ENGLISH_SOURCE_SECOND,
    },
]


CURRICULUM_META = {
    "grade": "六年级",
    "scope_note": "仅使用公开教材目录和人工整理知识点，不存储教材正文。",
    "sources": [
        {
            "label": "上海市教委 2025 年秋季中小学教学用书目录",
            "url": "https://edu.sh.gov.cn/cmsres/3e/3e72a3d43d05429e9325d4b57cf499c3/f1b8612f871c899afe807885f18ad0aa.pdf",
        },
        {
            "label": "上海市教委 2026 年春季中小学教学用书目录",
            "url": "https://edu.sh.gov.cn/cmsres/3a/3a555417ed2b47a38f730ca8c9f10881/9ba8430bf7e54d3e19fce9c17b45f5fb.pdf",
        },
    ],
}
