"""上海初中单元复习卷的公开目录范围与人工整理知识点。"""

GRADE_6 = "六年级"
GRADE_7 = "七年级"
GRADE_8 = "八年级"
GRADE = GRADE_6
MATH_SOURCE_FIRST = "上海六年级第一学期《义务教育教科书（五·四学制）·数学》2024 年审定版目录"
MATH_SOURCE_SECOND = "上海六年级第二学期《义务教育教科书（五·四学制）·数学》2024 年审定版目录"
ENGLISH_SOURCE_FIRST = "上海六年级第一学期《义务教育教科书（五·四学制）·英语》2024 年审定版目录"
ENGLISH_SOURCE_SECOND = "上海六年级第二学期《义务教育教科书（五·四学制）·英语》2024 年审定版目录"
MATH_7_SOURCE_FIRST = "上海七年级第一学期《义务教育教科书（五·四学制）·数学》，册次依据上海市教委 2025 年秋季教学用书目录确认"
MATH_7_SOURCE_SECOND = "上海七年级第二学期《义务教育教科书（五·四学制）·数学》，册次依据上海市教委 2026 年春季教学用书目录确认"
ENGLISH_7_SOURCE_FIRST = "上海七年级第一学期《义务教育教科书（五·四学制）·英语》，册次依据上海市教委 2025 年秋季教学用书目录确认"
ENGLISH_7_SOURCE_SECOND = "上海七年级第二学期《义务教育教科书（五·四学制）·英语》，册次依据上海市教委 2026 年春季教学用书目录确认"
MATH_8_SOURCE_FIRST = "上海八年级第一学期《义务教育教科书（五·四学制）·数学》，册次依据上海市教委 2025 年秋季教学用书目录确认"
MATH_8_SOURCE_SECOND = "上海八年级第二学期《义务教育教科书（五·四学制）·数学》，册次依据上海市教委 2026 年春季教学用书目录列示（目录标注待审）"
ENGLISH_8_SOURCE_FIRST = "上海八年级第一学期《义务教育教科书（五·四学制）·英语》，册次依据上海市教委 2025 年秋季教学用书目录确认"
ENGLISH_8_SOURCE_SECOND = "上海八年级第二学期《义务教育教科书（五·四学制）·英语》，册次依据上海市教委 2026 年春季教学用书目录列示（目录标注待审）"


def unit(unit_id, subject, semester, title, knowledge_points, source_note, grade=GRADE):
    return {
        "id": unit_id,
        "grade": grade,
        "subject": subject,
        "semester": semester,
        "title": title,
        "knowledge_points": knowledge_points,
        "source_note": source_note,
    }


CURRICULUM_UNITS = [
    unit(
        "math-6a-rational-numbers",
        "math",
        "first",
        "第1章 有理数",
        ["有理数", "有理数的加法与减法", "有理数的乘法与除法", "有理数的乘方", "有理数的混合运算"],
        MATH_SOURCE_FIRST,
    ),
    unit(
        "math-6a-algebraic-expressions",
        "math",
        "first",
        "第2章 简单的代数式",
        ["用字母表示数", "代数式", "一次式"],
        MATH_SOURCE_FIRST,
    ),
    unit(
        "math-6a-linear-equation",
        "math",
        "first",
        "第3章 一元一次方程",
        ["方程与列方程", "一元一次方程及其解法", "一元一次方程的应用"],
        MATH_SOURCE_FIRST,
    ),
    unit(
        "math-6a-lines-angles",
        "math",
        "first",
        "第4章 线段与角",
        ["线段", "角"],
        MATH_SOURCE_FIRST,
    ),
    unit(
        "math-6b-ratio-proportion",
        "math",
        "second",
        "第5章 比与比例",
        ["比、比例及其性质", "百分数"],
        MATH_SOURCE_SECOND,
    ),
    unit(
        "math-6b-circle-sector",
        "math",
        "second",
        "第6章 圆与扇形",
        ["圆的周长与弧长", "圆与扇形的面积"],
        MATH_SOURCE_SECOND,
    ),
    unit(
        "math-6b-probability-statistics",
        "math",
        "second",
        "第7章 可能性与统计图表",
        ["随机现象及其结果的可能性", "数据的收集、整理与表达", "百分数的统计意义"],
        MATH_SOURCE_SECOND,
    ),
    unit(
        "math-6b-cylinder-cone",
        "math",
        "second",
        "第8章 圆柱与圆锥",
        ["圆柱及其侧面展开图", "圆锥及其侧面展开图"],
        MATH_SOURCE_SECOND,
    ),
    unit(
        "math-6b-linear-systems",
        "math",
        "second",
        "第9章 二元一次方程组",
        ["二元一次方程组的概念", "二元一次方程组的解法", "二元一次方程组的应用", "简单的三元一次方程组"],
        MATH_SOURCE_SECOND,
    ),
    unit(
        "english-6a-u1-school-life",
        "english",
        "first",
        "Unit 1 School life",
        ["school subjects", "school activities", "a school day", "my school life", "my dream school"],
        ENGLISH_SOURCE_FIRST,
    ),
    unit(
        "english-6a-u2-family-ties",
        "english",
        "first",
        "Unit 2 Family ties",
        ["family relations", "family members", "family duties", "family time", "a family poster"],
        ENGLISH_SOURCE_FIRST,
    ),
    unit(
        "english-6a-u3-food",
        "english",
        "first",
        "Unit 3 Food",
        ["food groups", "healthy food choices", "food for love", "my healthy dish", "a healthy school lunch menu"],
        ENGLISH_SOURCE_FIRST,
    ),
    unit(
        "english-6a-u4-sports",
        "english",
        "first",
        "Unit 4 Sports",
        ["sports activities", "sports safety", "sports fun", "sporting moments", "sports for us"],
        ENGLISH_SOURCE_FIRST,
    ),
    unit(
        "english-6a-u5-animals",
        "english",
        "first",
        "Unit 5 Animals and us",
        ["amazing animals", "getting along with animals", "a day on the farm", "my favourite animal", "an animal club logo"],
        ENGLISH_SOURCE_FIRST,
    ),
    unit(
        "english-6a-u6-travelling-china",
        "english",
        "first",
        "Unit 6 Travelling around China",
        ["a place to go", "ways of travelling", "young travellers", "my footprint", "a travel plan"],
        ENGLISH_SOURCE_FIRST,
    ),
    unit(
        "english-6b-u1-differences",
        "english",
        "second",
        "Unit 1 Everyone is different",
        ["noticing differences", "finding differences", "accepting differences", "showing differences", "future me"],
        ENGLISH_SOURCE_SECOND,
    ),
    unit(
        "english-6b-u2-rules",
        "english",
        "second",
        "Unit 2 Rules around us",
        ["signs and rules", "rules in different places", "a rule story", "an activity notice", "public signs and rules"],
        ENGLISH_SOURCE_SECOND,
    ),
    unit(
        "english-6b-u3-festivals",
        "english",
        "second",
        "Unit 3 Festivals across cultures",
        ["festival foods", "festival activities", "festival celebrations", "festival experiences", "a festival poster"],
        ENGLISH_SOURCE_SECOND,
    ),
    unit(
        "english-6b-u4-weather",
        "english",
        "second",
        "Unit 4 Weather and our lives",
        ["weather reports", "seasonal activities", "extreme weather", "weather and travel", "weather in life"],
        ENGLISH_SOURCE_SECOND,
    ),
    unit(
        "english-6b-u5-green-neighbourhood",
        "english",
        "second",
        "Unit 5 Green neighbourhood",
        ["a green song", "green ideas", "a green city", "greener experiences", "an ideal green neighbourhood"],
        ENGLISH_SOURCE_SECOND,
    ),
    unit(
        "english-6b-u6-famous-people",
        "english",
        "second",
        "Unit 6 Famous people in history",
        ["world changers", "life savers", "great storytellers", "great minds", "famous people in history"],
        ENGLISH_SOURCE_SECOND,
    ),
    unit(
        "math-7a-polynomial-addition",
        "math",
        "first",
        "第10章 整式的加减",
        ["整式", "合并同类项", "整式的加减"],
        MATH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "math-7a-polynomial-multiplication",
        "math",
        "first",
        "第11章 整式的乘除",
        ["整式的乘法", "乘法公式", "整式的除法"],
        MATH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "math-7a-factoring",
        "math",
        "first",
        "第12章 因式分解",
        ["因式分解", "提公因式法", "公式法", "十字相乘法"],
        MATH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "math-7a-rational-expressions",
        "math",
        "first",
        "第13章 分式",
        ["分式", "分式的基本性质", "分式的运算", "分式方程"],
        MATH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "math-7a-transformations",
        "math",
        "first",
        "第14章 图形的运动",
        ["平移", "旋转", "轴对称", "中心对称"],
        MATH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "math-7b-linear-inequalities",
        "math",
        "second",
        "第15章 一元一次不等式",
        ["不等式及其性质", "一元一次不等式", "一元一次不等式组"],
        MATH_7_SOURCE_SECOND,
        grade=GRADE_7,
    ),
    unit(
        "math-7b-lines",
        "math",
        "second",
        "第16章 相交线与平行线",
        ["相交线", "平行线", "命题与证明"],
        MATH_7_SOURCE_SECOND,
        grade=GRADE_7,
    ),
    unit(
        "math-7b-triangles",
        "math",
        "second",
        "第17章 三角形",
        ["三角形的有关概念", "三角形的内角和", "全等三角形及其性质", "三角形全等的判定"],
        MATH_7_SOURCE_SECOND,
        grade=GRADE_7,
    ),
    unit(
        "math-7b-isosceles-triangles",
        "math",
        "second",
        "第18章 等腰三角形",
        ["等腰三角形的性质", "等腰三角形的判定", "等边三角形", "线段垂直平分线"],
        MATH_7_SOURCE_SECOND,
        grade=GRADE_7,
    ),
    unit(
        "english-7a-u1-friendship",
        "english",
        "first",
        "Unit 1 Friendship",
        ["making friends", "qualities of a good friend", "friendship stories", "friendship communication"],
        ENGLISH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "english-7a-u2-school-life",
        "english",
        "first",
        "Unit 2 School life",
        ["school routines", "school activities", "school clubs", "describing school life"],
        ENGLISH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "english-7a-u3-seasons",
        "english",
        "first",
        "Unit 3 The seasons",
        ["seasonal weather", "seasonal activities", "changes in nature", "describing a season"],
        ENGLISH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "english-7a-u4-earth",
        "english",
        "first",
        "Unit 4 The Earth",
        ["the natural world", "environmental problems", "protecting the Earth", "green actions"],
        ENGLISH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "english-7a-u5-space",
        "english",
        "first",
        "Unit 5 Off to space",
        ["the solar system", "space travel", "life in space", "a space mission"],
        ENGLISH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "english-7a-u6-asia",
        "english",
        "first",
        "Unit 6 Travelling around Asia",
        ["Asian destinations", "travel experiences", "travel plans", "introducing a place"],
        ENGLISH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "english-7a-u7-after-school",
        "english",
        "first",
        "Unit 7 Fun after school",
        ["after-school activities", "clubs and interests", "making invitations", "planning an activity"],
        ENGLISH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "english-7a-u8-collecting",
        "english",
        "first",
        "Unit 8 Collecting as a hobby",
        ["collections", "hobbies and interests", "reasons for collecting", "introducing a collection"],
        ENGLISH_7_SOURCE_FIRST,
        grade=GRADE_7,
    ),
    unit(
        "english-7b-u1-music",
        "english",
        "second",
        "Unit 1 Music",
        ["music and musicians", "music preferences", "the power of music", "introducing music"],
        ENGLISH_7_SOURCE_SECOND,
        grade=GRADE_7,
    ),
    unit(
        "english-7b-u2-communication",
        "english",
        "second",
        "Unit 2 Language and communication",
        ["ways of communication", "communication skills", "group communication", "introducing oneself"],
        ENGLISH_7_SOURCE_SECOND,
        grade=GRADE_7,
    ),
    unit(
        "english-7b-u3-helping-hand",
        "english",
        "second",
        "Unit 3 A helping hand",
        ["everyday heroes", "helping others", "emergencies", "showing thankfulness"],
        ENGLISH_7_SOURCE_SECOND,
        grade=GRADE_7,
    ),
    unit(
        "english-7b-u4-honesty",
        "english",
        "second",
        "Unit 4 Honesty",
        ["honest choices", "stories about honesty", "keeping promises", "actions and consequences"],
        ENGLISH_7_SOURCE_SECOND,
        grade=GRADE_7,
    ),
    unit(
        "english-7b-u5-wild-animals",
        "english",
        "second",
        "Unit 5 Wild animals",
        ["wild animal species", "wildlife safety", "reading about wild animals", "wildlife conservation"],
        ENGLISH_7_SOURCE_SECOND,
        grade=GRADE_7,
    ),
    unit(
        "english-7b-u6-trees",
        "english",
        "second",
        "Unit 6 Trees",
        ["forests", "the value of trees", "protecting trees", "trees around us"],
        ENGLISH_7_SOURCE_SECOND,
        grade=GRADE_7,
    ),
    unit(
        "math-8a-real-numbers",
        "math",
        "first",
        "第19章 实数",
        ["平方根与立方根", "实数", "实数的大小比较", "实数的运算"],
        MATH_8_SOURCE_FIRST,
        grade=GRADE_8,
    ),
    unit(
        "math-8a-radicals",
        "math",
        "first",
        "第20章 二次根式",
        ["二次根式及其性质", "最简二次根式", "二次根式的乘除", "二次根式的加减"],
        MATH_8_SOURCE_FIRST,
        grade=GRADE_8,
    ),
    unit(
        "math-8a-quadratic-equations",
        "math",
        "first",
        "第21章 一元二次方程",
        ["一元二次方程的概念", "一元二次方程的解法", "一元二次方程的判别式", "一元二次方程的根与系数的关系", "一元二次方程的应用"],
        MATH_8_SOURCE_FIRST,
        grade=GRADE_8,
    ),
    unit(
        "math-8a-right-triangles",
        "math",
        "first",
        "第22章 直角三角形",
        ["直角三角形的性质", "直角三角形全等的判定", "角平分线", "勾股定理", "勾股定理的逆定理"],
        MATH_8_SOURCE_FIRST,
        grade=GRADE_8,
    ),
    unit(
        "math-8b-quadrilaterals",
        "math",
        "second",
        "第23章 四边形",
        ["多边形", "平行四边形", "矩形、菱形与正方形", "三角形的中位线与重心"],
        MATH_8_SOURCE_SECOND,
        grade=GRADE_8,
    ),
    unit(
        "math-8b-coordinate-plane",
        "math",
        "second",
        "第24章 平面直角坐标系",
        ["平面直角坐标系", "点的坐标与象限", "两点间的距离公式", "平移与轴对称的坐标变化"],
        MATH_8_SOURCE_SECOND,
        grade=GRADE_8,
    ),
    unit(
        "math-8b-linear-functions",
        "math",
        "second",
        "第25章 一次函数",
        ["变量与函数", "正比例函数", "一次函数", "一次函数的图像与性质", "一次函数的应用"],
        MATH_8_SOURCE_SECOND,
        grade=GRADE_8,
    ),
    unit(
        "math-8b-inverse-functions",
        "math",
        "second",
        "第26章 反比例函数",
        ["反比例函数", "反比例函数的图像与性质", "反比例函数的应用"],
        MATH_8_SOURCE_SECOND,
        grade=GRADE_8,
    ),
    unit(
        "english-8a-u1-water",
        "english",
        "first",
        "Unit 1 Water",
        ["the water cycle", "water use", "water conservation", "describing a process"],
        ENGLISH_8_SOURCE_FIRST,
        grade=GRADE_8,
    ),
    unit(
        "english-8a-u2-digital-life",
        "english",
        "first",
        "Unit 2 Digital life",
        ["digital devices", "online habits", "digital safety", "describing digital life"],
        ENGLISH_8_SOURCE_FIRST,
        grade=GRADE_8,
    ),
    unit(
        "english-8a-u3-curious-minds",
        "english",
        "first",
        "Unit 3 Curious minds",
        ["asking questions", "scientific discovery", "experiments and observation", "explaining findings"],
        ENGLISH_8_SOURCE_FIRST,
        grade=GRADE_8,
    ),
    unit(
        "english-8a-u4-then-now",
        "english",
        "first",
        "Unit 4 Then and now",
        ["past and present", "changes over time", "comparing lifestyles", "describing development"],
        ENGLISH_8_SOURCE_FIRST,
        grade=GRADE_8,
    ),
    unit(
        "english-8a-u5-teamwork",
        "english",
        "first",
        "Unit 5 Teamwork",
        ["team roles", "cooperation", "solving problems together", "effective communication"],
        ENGLISH_8_SOURCE_FIRST,
        grade=GRADE_8,
    ),
    unit(
        "english-8a-u6-future",
        "english",
        "first",
        "Unit 6 Life in the future",
        ["future entertainment", "future travel", "future living", "expressing predictions"],
        ENGLISH_8_SOURCE_FIRST,
        grade=GRADE_8,
    ),
    unit(
        "english-8b-u1-art",
        "english",
        "second",
        "Unit 1 Art and artists",
        ["art forms", "artists and artworks", "expressing art preferences", "introducing an artist"],
        ENGLISH_8_SOURCE_SECOND,
        grade=GRADE_8,
    ),
    unit(
        "english-8b-u2-inventions",
        "english",
        "second",
        "Unit 2 Great inventions and discoveries",
        ["great inventions", "important discoveries", "explaining an invention", "the impact of inventions"],
        ENGLISH_8_SOURCE_SECOND,
        grade=GRADE_8,
    ),
    unit(
        "english-8b-u3-money",
        "english",
        "second",
        "Unit 3 Money",
        ["forms of money", "spending and saving", "the history of money", "responsible money choices"],
        ENGLISH_8_SOURCE_SECOND,
        grade=GRADE_8,
    ),
    unit(
        "english-8b-u4-fashion",
        "english",
        "second",
        "Unit 4 Fashion",
        ["clothing and styles", "fashion choices", "describing trends", "sustainable fashion"],
        ENGLISH_8_SOURCE_SECOND,
        grade=GRADE_8,
    ),
    unit(
        "english-8b-u5-natural-disasters",
        "english",
        "second",
        "Unit 5 Natural disasters",
        ["types of natural disasters", "warnings and safety", "disaster news reports", "emergency preparation"],
        ENGLISH_8_SOURCE_SECOND,
        grade=GRADE_8,
    ),
    unit(
        "english-8b-u6-friendship",
        "english",
        "second",
        "Unit 6 Friendship",
        ["qualities of friendship", "resolving conflict", "supporting friends", "friendship writing"],
        ENGLISH_8_SOURCE_SECOND,
        grade=GRADE_8,
    ),
]


CURRICULUM_META = {
    "grade": GRADE,
    "default_grade": GRADE,
    "available_grades": [GRADE_6, GRADE_7, GRADE_8],
    "grades": [
        {"value": "六年级", "status": "available", "note": "2024 年审定新版目录已核对"},
        {"value": "七年级", "status": "available", "note": "2025 秋季、2026 春季市教委目录已核对"},
        {"value": "八年级", "status": "available", "note": "2025 秋季目录已核对；2026 春季下册目录标注待审"},
        {"value": "九年级", "status": "pending", "note": "需区分学校使用的英语版本"},
    ],
    "edition_note": "六至八年级数学和英语使用依据 2022 年版课程标准修订、分册陆续审定启用的五·四学制教材；八年级下册在 2026 年春季目录中标注待审。",
    "scope_note": "仅使用公开教材目录和人工整理知识点，不存储教材正文。",
    "sources": [
        {
            "semester": "first",
            "label": "上海市教委 2025 年秋季中小学教学用书目录",
            "url": "https://edu.sh.gov.cn/cmsres/2d/2dc160ca4658483e8eaaf76e8f945637/28a7fabd94b936378d6dd4c271c12ad8.pdf",
        },
        {
            "semester": "second",
            "label": "上海市教委 2026 年春季中小学教学用书目录",
            "url": "https://edu.sh.gov.cn/cmsres/3a/3a555417ed2b47a38f730ca8c9f10881/9ba8430bf7e54d3e19fce9c17b45f5fb.pdf",
        },
    ],
}
